spring.application.name=primerProyecto

# URL estructurada para Spring Boot usando el Pooler en puerto 6543
spring.datasource.url=jdbc:postgresql://://supabase.com
spring.datasource.username=postgres.vrxgjsjwtcdnlginccfz
spring.datasource.password=Dragon10++*Kendarg

spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate y JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuración JWT
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000
